### ISSUE TITLE
wrong number of arguments error with simplecov 0.11.0

### ISSUE THREAD

**Issue by alexjfisher** [garethr/puppet-module-skeleton#99]
Simplecov 0.11.0 has just been [released] (https://github.com/colszowka/simplecov/releases/tag/v0.11.0)

This appears to have broken ```bundle exec rake spec```

eg
```
/home/alex/fme/spec/spec_helper.rb:13:in `block in <top (required)>': [DEPRECATION] ::[] is deprecated. Use ::new instead.
/home/alex/.rvm/gems/ruby-1.9.3-p551/gems/simplecov-0.11.0/lib/simplecov/formatter/multi_formatter.rb:17:in `new': wrong number of arguments (2 for 1) (ArgumentError)
        from /home/alex/.rvm/gems/ruby-1.9.3-p551/gems/simplecov-0.11.0/lib/simplecov/formatter/multi_formatter.rb:28:in `[]'
        from /home/alex/fme/spec/spec_helper.rb:13:in `block in <top (required)>'
        from /home/alex/.rvm/gems/ruby-1.9.3-p551/gems/docile-1.1.5/lib/docile/execution.rb:25:in `instance_exec'
        from /home/alex/.rvm/gems/ruby-1.9.3-p551/gems/docile-1.1.5/lib/docile/execution.rb:25:in `exec_in_proxy_context'
        from /home/alex/.rvm/gems/ruby-1.9.3-p551/gems/docile-1.1.5/lib/docile.rb:43:in `dsl_eval'
        from /home/alex/.rvm/gems/ruby-1.9.3-p551/gems/simplecov-0.11.0/lib/simplecov/configuration.rb:151:in `configure'
        from /home/alex/.rvm/gems/ruby-1.9.3-p551/gems/simplecov-0.11.0/lib/simplecov.rb:39:in `start'
        from /home/alex/fme/spec/spec_helper.rb:10:in `<top (required)>'
        from /home/alex/fme/spec/classes/api_settings_spec.rb:1:in `require'
        from /home/alex/fme/spec/classes/api_settings_spec.rb:1:in `<top (required)>'
        from /home/alex/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load'
        from /home/alex/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `block in load_spec_files'
        from /home/alex/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `each'
        from /home/alex/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load_spec_files'
        from /home/alex/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96:in `setup'
        from /home/alex/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
        from /home/alex/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
        from /home/alex/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
        from /home/alex/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.1.7/exe/rspec:4:in `<main>'
```

I'm not sure what the fix is, but I guess the spec_helper.rb needs tweaking.

Kind Regards,
Alex

**Comment by garethr** [comment]
@alexjfisher thanks for the heads up. Should be fixed in https://github.com/garethr/puppet-module-skeleton/commit/087c2a3540a6aef40062641e90cfb4a3bdaaa840

**Comment by alexjfisher** [comment]
ha.  You're too quick!  I had my own PR on the way!

**Comment by alexjfisher** [comment]
For what it's worth, this was my commit. https://github.com/alexjfisher/puppet-module-skeleton/commit/6cb198c5f037b63431df970efc4dc2716d94c474 :)

I'll test your change works too.

**Comment by alexjfisher** [comment]
https://github.com/garethr/puppet-module-skeleton/commit/087c2a3540a6aef40062641e90cfb4a3bdaaa840 works fine for me too.  So I guess there's no real advantage of using `formatters` over `formatter`?

**Comment by rnelson0** [comment]
FYI I used simplecov 0.11.0 all weekend without an issue (and so did Travis). Is this maybe related to simplecov + ruby version? I'm still on ruby 1.9.3. Just curious.

**Comment by alexjfisher** [comment]
That's odd.  I'm definitely using ruby 1.9.3 too (as shown in the error trace above).
